export const userActionTypes = {
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
  SIGNIN_SUCCESS: "GOOGLE_SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "GOOGLE_SIGNIN_FAILURE",
  EMAIL_SIGNIN_START: "EMAIL_SIGNIN_START",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
};
